name: Basic Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show system info
        run: uname -a

      - name: Show files in repository
        run: ls -l

      - name: Print custom message
        run: echo "This is my second GitHub Actions task"
